admin_password: ffff
rancher_version: v2.6.3
ROS_version: 1.5.1
hostname: rancher-master
node:
  count: 2
  cpus: 1
  memory: 2048
ip:
  node: 192.168.0.151
linked_clones: true
net:
  network_type: public_network
